name: CI
on: [pull_request, push]
permissions:
  contents: read
defaults:
  run:
    shell: bash -euxo pipefail
env:
  TZ: Europe/Zurich
  PYTHONHASHSEED: "0"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python for slashc
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install PyYAML jsonschema

      - name: Validate slash command structure
        run: |
          mkdir -p .slash
          ./tools/slashc.py validate .slash/*.md

      - name: Intelligent validation with Claude
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            Review .slash/build.md and .slash/test.md. These are production CI/CD commands.

            Reject if ANY of these are true:
            1. Contains placeholder echo statements instead of real npm commands
            2. Container images are not pinned with SHA256 digests
            3. Does not use actual project build/test commands from package.json

            Respond with: VALID or INVALID with explanation.
  build:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python for slashc
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Python dependencies
        run: pip install PyYAML jsonschema
      - name: Run /build
        run: ./tools/slashc.py run .slash/build.md
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: .out/build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python for slashc
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Python dependencies
        run: pip install PyYAML jsonschema
      - name: Run /test
        run: ./tools/slashc.py run .slash/test.md
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: .out/coverage